"""Task 6K.1 final pipeline stage: slim the committed artifacts.

The measurement scripts intentionally keep full per-tile evidence in their output. For the repository
the per-tile rows are moved into the gitignored cache and only the aggregates stay in `evaluation/`,
so the committed JSON stays small while nothing is lost locally (and everything remains reproducible
by re-running the scripts against the read-only sources).

Run after every measurement script, before committing:

    python scripts/task6k1_slim_artifacts.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
for extra in (REPO_ROOT, REPO_ROOT / "scripts"):
    if str(extra) not in sys.path:
        sys.path.insert(0, str(extra))

from task6k1_common import CACHE_DIR, EVAL, write_json  # noqa: E402

#: artifact -> keys whose (large) values are moved to the gitignored cache
MOVE_KEYS = {
    "task6k1_vector_instance_stats.json": ("per_tile",),
    "task6k1_vector_raster_alignment.json": ("rows", "empty_rows"),
    "task6k1_vector_vs_pseudo_matching.json": ("per_tile",),
    "task6k1_whole_image_georef.json": (),
    "task6k1_tile_mapping.json": (),
}


def main() -> int:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    for name, keys in MOVE_KEYS.items():
        path = EVAL / name
        if not path.is_file():
            continue
        payload = json.loads(path.read_text(encoding="utf-8"))
        moved = {}
        for key in keys:
            if key in payload:
                moved[key] = payload.pop(key)
        if moved:
            cache_path = CACHE_DIR / f"{name.replace('.json', '')}_per_tile.json"
            write_json(cache_path, moved)
            payload["per_tile_detail"] = {
                "moved_to_gitignored_cache": str(cache_path.relative_to(REPO_ROOT)).replace("\\", "/"),
                "keys": sorted(moved),
                "rows": {key: len(value) for key, value in moved.items()},
                "note": (
                    "per-tile rows are kept out of the repository to keep the committed JSON small; "
                    "they are regenerated by re-running the measurement scripts"
                ),
            }
            write_json(path, payload)
            print(
                f"[task6k1.slim] {name}: moved {sorted(moved)} "
                f"({path.stat().st_size / 1024:.0f} KiB now)",
                flush=True,
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
